# Generated by Django 4.1 on 2023-04-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workoutinfo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_membership",
        ),
        migrations.RemoveConstraint(
            model_name="payment",
            name="unique_payment",
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("member", "start_date", "end_date"), name="unique_membership"
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("member", "payment_date"), name="unique_payment"
            ),
        ),
    ]
