# Generated by Django 4.1 on 2023-04-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workoutinfo", "0002_remove_membership_unique_membership_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="unique_payment",
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("member",), name="unique_payment"
            ),
        ),
    ]
