# Generated by Django 4.1 on 2023-04-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workoutinfo", "0004_remove_payment_unique_payment_payment_unique_payment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="unique_payment",
        ),
    ]
