# Generated by Django 4.1 on 2023-04-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workoutinfo", "0004_remove_payment_unique_payment_payment_unique_payment"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="payment",
            name="unique_payment",
        ),
        migrations.AlterField(
            model_name="workoutinfo",
            name="date",
            field=models.DateField(),
        ),
    ]
