# Generated by Django 4.1 on 2023-04-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workoutinfo", "0006_alter_payment_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutritionplan",
            name="meal_timing",
        ),
    ]
